Check that origin/master exists before using it
And warn if no upstream is found, so the subsequent git errors make more
sense

diff --git a/git-tracks b/git-tracks
--- a/git-tracks
+++ b/git-tracks
@@ -39,6 +39,8 @@ if [[ "$remote" != "." ]]; then
   echo "${remote:?}/${remoteBranch:?}"
 elif [[ "$remoteBranch" != "" ]]; then
   echo "${remoteBranch:?}"
-elif [[ "$use_default" == 1 ]]; then
-  echo "origin/master"
+elif [[ "$use_default" == 1 ]] && git rev-parse origin/master &>/dev/null; then
+  echo origin/master
+else
+  echo >&2 "Warning: Could not find a upstream for $branch"
 fi
