handle missing python2 gracefully
If python2 is missing, git-push-to-hg will fail after already modified the
mercurial repo state. So abort gracefully before starting on such case.

Scripts which are python(2) themselves will fail before starting. Currently
git-push-to-hg is the only bash script which invokes a python(2) script.

Also add a note at the README about handling it with Windows mozilla-build.

diff --git a/git-push-to-hg b/git-push-to-hg
--- a/git-push-to-hg
+++ b/git-push-to-hg
@@ -1,6 +1,15 @@
 #!/bin/bash
 set -e
 
+if ! hash python2 2> /dev/null; then
+  echo "'python2' is required but not found. Aborting."
+  if hash python 2> /dev/null; then
+    echo "'python' found at '$(which python)'."
+    echo "If using mozilla-build, you can copy it to 'python2.exe' at the same location."
+    echo "See README.markdown for more information."
+  fi
+fi
+
 # Push some commits from git to the git-temp qqueue in a given hg repository.
 # Note that this nukes the git-temp qqueue, if it exists.
 #
