Restore the behavior of |git tracks -d| for branches with no upstream set.
Fixes #36.

diff --git a/git-tracks b/git-tracks
--- a/git-tracks
+++ b/git-tracks
@@ -17,9 +17,18 @@
 
 if [[ "$1" == "-d" || "$1" == "--default" ]]; then
   branch=HEAD
+  use_default=1
 else
   branch=$1
+  use_default=0
 fi
 
 branchref=$(git rev-parse --symbolic-full-name $branch) || exit $?
-git for-each-ref --format='%(upstream:short)' $branchref
+remote=$(git for-each-ref --format='%(upstream:short)' $branchref)
+if [[ $remote != "" ]]; then
+  echo $remote
+elif [[ "$use_default" == 1 ]] && git rev-parse origin/master &>/dev/null; then
+  echo origin/master
+else
+  echo >&2 "Warning: Could not find a upstream for $branch"
+fi
